### ISSUE TITLE
Upgrade Bevy to 0.10.0

### ISSUE THREAD

**Issue by tibomogul** [tibomogul/adventure-encounters#4]
Did an initial effort on this, on the day of release. Unfortunately the build is complaining that bevy_ecs_tilemap TileStorage does not implement Component. Even though it obviously does as queries worked on 0.9.1. Parking this for now as to let the dust settle first.

**Comment by tibomogul** [comment]
Done. Need to track bevy_ecs_tilemap though.
